shoplineapp/helm-charts

cronjob/templates/cronjob.yaml

`helm install ~/github/helm-charts/cronjob --name grafana-backup --namespace grafana -f helm/grafana-backup.yaml --dry-run --debug`
```
Error: YAML parse error on cronjob/templates/cronjob.yaml: error converting YAML to JSON: yaml: line 28: could not find expected ':'
```

fix command null error

---

fluentd-cloudwatch/templates/daemonset.yaml

ec-eks-staging k8s版本為1.16
daemonSet apiVersion已經修改為 apps/v1
ref1: https://cloud.google.com/kubernetes-engine/docs/release-notes
ref2: https://github.com/kubernetes/kubernetes/issues/84782

update fluentd apiVersion for k8s 1.16

---

simple/templates/service.yaml

for prometheus-operater setting, that need label to get service monitor endpoint

service resource support setting label

---

cronjob/templates/cronjob.yaml
cronjob/values.yaml
simple/Chart.yaml
simple/templates/deployment.yaml
simple/values.yaml

helm diff shop-nc in ec-eks-db-preview result:
```
+       affinity:
+         nodeAffinity:
+           {}
+
+         podAffinity:
+           {}
+
+         podAntiAffinity:
+           preferredDuringSchedulingIgnoredDuringExecution:
+             - podAffinityTerm:
+                 labelSelector:
+                   matchExpressions:
+                   - key: app
+                     operator: In
+                     values:
+                     - shop-nc
+                 topologyKey: failure-domain.beta.kubernetes.io/zone
+               weight: 100
+             - podAffinityTerm:
+                 labelSelector:
+                   matchExpressions:
+                   - key: app
+                     operator: In
+                     values:
+                     - shop-nc …
```

deployment default prefer difference AZ/Node

---

simple/Chart.yaml
simple/templates/deployment.yaml

以下測試目的為這次更新後，所有更新場景皆可以不受影響．
測試一般deploy
helm2:
**helm diff upgrade shop-nc ~/github/helm-charts/simple --set-string deployment.containers.shop-nc.image.tag=616925d -f shop-nc.yaml -f cm-env.yaml -f secret-env.yaml**
```
+       affinity:
+         nodeAffinity:
+           {}
+
+         podAffinity:
+           {}
+
+         podAntiAffinity:
+           preferredDuringSchedulingIgnoredDuringExecution:
+             - podAffinityTerm:
+                 labelSelector:
+                   matchExpressions:
+                   - key: app
+                     operator: In
+                     values:
+                     - shop-nc
+                 topologyKey: failure-domain.beta.kubernetes.io/zone
+               weight: 100
+             - podAffinityTerm:
+ …
```

disable helm2 default allocate to difference az/node

---

simple/templates/deployment.yaml

Extending termination seconds to 61 as this is slightly longer then our general application requests' timeout

feat(terminationGrace):extend termination grace to 61

---

simple/Chart.yaml
simple/templates/servicemonitor.yaml
simple/values.yaml

Using helm to deploy service monitor resource for us would be nice!
The label has a default value `release: prometheus-operator` which can make the prometheus-operator pick up the service monitor.
Also, the service monitor should be put in `namespace: prometheus-operator` by default.
----------
Here is a nice article to introduce the prometheus / service monitor / service / pods
https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/troubleshooting.md#troubleshooting-servicemonitor-changes

add service monitor template

---

cronjob/.helmignore
fluentd-cloudwatch/.helmignore
simple/.helmignore

check re-package helm chart size:
before:(include *.tgz)
```shell
ls -al simple-0.4.0.tgz
-rw-r--r--   1 andychuang  staff  1014712 10 15 12:50 simple-0.4.0.tgz
tar -zxf simple-0.4.0.tgz
ls -al simple
drwxr-xr-x  11 andychuang  staff     352 10 15 12:42 .
drwxr-xr-x  13 andychuang  staff     416 10 15 12:42 ..
-rw-r--r--   1 andychuang  staff     125 10 14 12:05 Chart.yaml
-rw-r--r--   1 andychuang  staff   25631 10 14 12:05 simple-0.0.1.tgz
-rw-r--r--   1 andychuang  staff   31460 10 14 12:05 simple-0.0.2.tgz
-rw-r--r--   1 andychuang  staff   63285 10 14 12:05 simple-0.0.3.tgz
-rw-r--r--   1 andychuang  staff  126586 10 14 12:05 simple-0.1.0.tgz
-rw-r--r--   1 andychuang  staff  253347 10 14 12:05 simple-0.2.0.tgz
-rw-r--r--   1 andychuang  staff  507190 10 14 12:05 simple-0.3.0.tgz …
```

fix chart oversize issue

---

.github/workflows/update-chart.yaml
backburner/.helmignore
backburner/Chart.yaml
backburner/templates/_container.tpl
backburner/templates/deployment.yaml
backburner/templates/hpa.yaml
backburner/templates/serviceaccount.yaml
backburner/values.yaml

This chart will support create backburner workers more easier.  
For example, we can create our worker likes below:
```
name: our-service-worker
global:
image:
repository: *************/shopline/our-service
tag: **********
serviceaccount:
annotations:
eks.amazonaws.com/role-arn: ************/our-service-role
envFromConfigmap:
- name: our-service-env
envFromSecret:
- name: our-service-env
workers:
- queue: our-service-worker-1
- queue: our-service-worker-2
- queue: our-service-worker-3
```

feat(backburner) support create many ruby backburner workers

---

simple/Chart.yaml
simple/templates/deployment.yaml

If we use KEDA, we can skip setting replica in deployment.

fix(simple) prevent from setting replica if using KEDA

---

cronjob/Chart.yaml
cronjob/templates/serviceaccount.yaml
cronjob/values.yaml

- Allow cronjob chart accept `serviceaccount` (same case as simple chart)
- Allow cronjob chart accept `serviceaccount.name`

feat(cronjob): support serviceaccount

---

backburner/Chart.yaml
backburner/templates/deployment.yaml
backburner/values.yaml

Because admin worker may need specific node group to hosts the Pod ,so add nodeAffinity for backburner template

Add feature-nodeAffinity

---

simple/Chart.yaml
simple/templates/_ingress_multiple.tpl
simple/templates/_ingress_single.tpl
simple/values.yaml

The **extensions/v1beta1** and **networking.k8s.io/v1beta1** API versions of Ingress is no longer served as of v1.22.
- Migrate manifests and API clients to use the **networking.k8s.io/v1** API version, available since v1.19.
- All existing persisted objects are accessible via the new API
- Notable changes:
- `spec.backend` is renamed to `spec.defaultBackend`
- The backend `serviceName` field is renamed to `service.name`
- Numeric backend `servicePort` fields are renamed to `service.port.number`
- String backend `servicePort` fields are renamed to `service.port.name`
- `pathType` is now required for each specified path. Options are `Prefix`, `Exact`, and `ImplementationSpecific`. To match the undefined `v1beta1` behavior, use `ImplementationSpecific`.
reference: …

feat(ingress): update api version

---

eks/Chart.yaml
eks/templates/role_admin.yaml
eks/templates/role_custom.yaml
eks/templates/role_po.yaml
eks/templates/role_read_only.yaml
fluentd-cloudwatch/Chart.yaml
fluentd-cloudwatch/templates/service_account.yaml

The **rbac.authorization.k8s.io/v1beta1** API version of ClusterRole, ClusterRoleBinding, Role, and RoleBinding is no longer served as of v1.22.
* Migrate manifests and API clients to use the **rbac.authorization.k8s.io/v1** API version, available since v1.8.
* All existing persisted objects are accessible via the new APIs
* No notable changes

deprecate old rbac api

---

simple/Chart.yaml
simple/templates/pdb.yaml

1. `policy/v1beta1` for PodDisruptionBudget is no longer served as of v1.25[1].
2. `policy/v1` is supported since v1.21.
Differenece between `policy/v1` and `policy/v1beta` [2]:
```
Note: The behavior for an empty selector differs between the policy/v1beta1 and policy/v1 APIs for PodDisruptionBudgets. For policy/v1beta1 an empty selector matches zero pods, while for policy/v1 an empty selector matches every pod in the namespace.
```
As we do not have empty selector, we can just update to v1.
[1] https://kubernetes.io/docs/reference/using-api/deprecation-guide/#poddisruptionbudget-v125
[2] https://kubernetes.io/docs/tasks/run-application/configure-pdb/#specifying-a-poddisruptionbudget

Update pdb api version

---

cronjob/Chart.yaml
cronjob/templates/pdb.yaml
cronjob/values.yaml

Aimed to add pdb to tackle argo cronworkflow pods scheduled right before karpenter decides to delete a node, which does not respect the karpenter's do-no-evict annotation

feat(cronjob): add pdb template and values

---

cronjob/Chart.yaml
cronjob/templates/_exit_handler_healthcheck_io.tpl
cronjob/templates/_exit_handler_slack_app.tpl

1. 2023/11/12 UTC+8 dockerhub down
2. we might encounter dockerhub ratelimit
so change the registry to private one.

cronjob: use curl from private registry instead of docker.io

---

simple/Chart.yaml
simple/templates/_container.tpl

Add support for startupProbe to facilitate protecting slow start containers 
ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes

feat: container add support for startupProbe

---

simple/Chart.yaml
simple/templates/_container.tpl

support downward api in deployment
reference: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information/
how to user
example:
```
containers:
mongodb-sink-connector:
envFromFieldRefs:
- name: CONNECT_REST_ADVERTISED_HOST_NAME
fieldPath: status.podIP
```
output:
```
containers:
- name: mongodb-sink-connector
image: "xxxxxx"
env:
- name: CONNECT_REST_ADVERTISED_HOST_NAME
valueFrom:
fieldRef:
fieldPath: status.podIP
```

feat(deployment): support downward api

---

simple/Chart.yaml
simple/templates/_ingress_multiple.tpl
simple/templates/_ingress_single.tpl

無 alb.ingress.kubernetes.io/certificate-arn:
```
helm diff upgrade api ../simple --allow-unreleased -n core
core, api, Ingress (networking.k8s.io) has changed:
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
name: api
labels:
businessid: "000000042493042706"
annotations:
alb.ingress.kubernetes.io/healthcheck-interval-seconds: "61"
alb.ingress.kubernetes.io/healthcheck-path: /health_check
alb.ingress.kubernetes.io/healthcheck-timeout-seconds: "60"
alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}]'
alb.ingress.kubernetes.io/load-balancer-attributes: access_logs.s3.enabled=true,access_logs.s3.bucket=aws-service-logs,access_logs.s3.prefix=elb/api-production,idle_timeout.timeout_seconds=70,deletion_protection.enabled=true
alb.ingress.kubernetes.io/load-balancer-name: …
```

feat: ssl policy add acm-arn condition

---

simple/Chart.yaml
simple/templates/_ingress_multiple.tpl
simple/templates/_ingress_single.tpl
simple/tests/ingress_test.yaml

```
helm unittest simple
PASS  Ingress Test	simple/tests/ingress_test.yaml
Charts:      1 passed, 1 total
Test Suites: 1 passed, 1 total
Tests:       7 passed, 7 total
Snapshot:    0 passed, 0 total
Time:        44.249208ms
```
Few testing result from multiple ingress:
1.  appending businessid on the tag annotations:
```
+     alb.ingress.kubernetes.io/tags: "Environment=production,ManagedBy=Terraform,ProjectName=Cst Menu Hidden,TeamName=CST,IngressName=api,businessid=00123"
```
2. already existing businessid on the tag annotaions:
```
alb.ingress.kubernetes.io/tags: Environment=production,ManagedBy=Terraform,ProjectName=Cst Menu Hidden,TeamName=CST,IngressName=api,businessid=00123
```
3. not having tag annotations at all:
```
+     alb.ingress.kubernetes.io/tags: "businessid=00123"
```

 fix: adding alb businessid if original tags doesnt contain businessid tag

---

simple/Chart.yaml
simple/templates/_container.tpl
simple/templates/_container_legacy.tpl

* To avoid HTTP 502 error during AWS LB controller performing the `DeregisterTargets` API.

feat: update default preStop hook sleep from 15s to 60s

---

backburner/Chart.yaml
backburner/templates/_container.tpl
backburner/values.yaml

- Added parameter `garbage` to support configuring GC per forked worker
- Updated to use rake task instead of cli to run backburner to support configuring GC globally using environment variables

feat(backburner): add support for garbage limit
